/**
 * Vercel serverless entry: forwards to the Nest app.
 * The _backend/ directory is copied from backend/dist/ during vercel-build.
 *
 * IMPORTANT: the require of ./_backend-manifest below is a workaround for
 * Vercel's Node File Tracer, which was trimming transitive submodules under
 * api/_backend/ out of the Lambda bundle even with
 * `includeFiles: "api/_backend/**\/*"` in vercel.json. Cold start then
 * threw
 *   "Cannot find module './auth.service'"
 *   from api/_backend/auth/auth.controller.js
 * and every route returned FUNCTION_INVOCATION_FAILED.
 *
 * The manifest file is auto-generated by scripts/generate-api-manifest.js
 * during vercel-build (after backend/dist is copied to api/_backend/). It
 * contains a static require() for every compiled .js file, which NFT is
 * guaranteed to pick up.
 */
require("./_backend-manifest");

module.exports = require("./_backend/serverless.js").default;
